services:
  - type: web_service
    name: livestream-w2-gaules
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand:
    startCommand:
    envVars:
      - key: PORT
        value: "10000"
      - key: DEEPL_API_KEY
        fromDatabase: deepl_key_secret
      - key: SPEECHIFY_API_KEY
        fromDatabase: speechify_key_secret
      - key: SPEECHIFY_VOICE_ID
        fromDatabase: speechify_voice_id
      - key: OPENAI_API_KEY
        fromDatabase: openai_key_secret
    autoDeploy: true
    public: true
